FROM python:3.11-slim

WORKDIR /app

RUN useradd -m appuser

COPY ./telegram-notifier/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./telegram-notifier/ .

USER appuser

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]