version: '3.8'

services:
  farzone:
    build:
      context: .
      dockerfile: Dockerfile.farzone
    environment:
      - DEBUG=${DEBUG:-False}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - SECRET_KEY=${SECRET_KEY}
      - YANDEX_MAPS_API_KEY=${YANDEX_MAPS_API_KEY}
      - NOTIFIER_URL=${NOTIFIER_URL:-http://notifier:8001/notifications/}
      - NOTIFIER_API_KEY=${NOTIFIER_API_KEY}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
    volumes:
      - ./farzone:/app
      - ./farzone/staticfiles:/app/staticfiles
      - ./farzone/media:/app/media
      - ./farzone/db:/app/db
    depends_on:
      - redis
    networks:
      - ttforum-network

  notifier:
    build:
      context: .
      dockerfile: Dockerfile.notifier
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./telegram-notifier:/app
    depends_on:
      - redis
    networks:
      - ttforum-network

  redis:
    image: redis:7
    networks:
      - ttforum-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./farzone/staticfiles:/app/staticfiles
      - ./farzone/media:/app/media
      - ./farzone/db:/app/db
    depends_on:
      - farzone
      - notifier
    networks:
      - ttforum-network

networks:
  ttforum-network:
    driver: bridge