# Используем официальный образ Python
FROM python:3.11-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем зависимости
COPY telegram-notifier/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект telegram-notifier
COPY telegram-notifier/ .

# Открываем порт для FastAPI
EXPOSE 8001

# Запускаем Uvicorn для FastAPI
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]