version: '3.8'

services:
  farzone:
    build:
      context: .
      dockerfile: Dockerfile.farzone
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,*.onrender.com
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./farzone:/app
      - ./farzone/staticfiles:/app/staticfiles
      - ./farzone/media:/app/media
      - ./farzone/db.sqlite3:/app/db.sqlite3
    depends_on:
      - redis
    networks:
      - ttforum-network

  notifier:
    build:
      context: .
      dockerfile: Dockerfile.notifier
    volumes:
      - ./telegram-notifier:/app
    depends_on:
      - redis
    networks:
      - ttforum-network

  redis:
    image: redis:7
    networks:
      - ttforum-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./farzone/staticfiles:/app/staticfiles
      - ./farzone/media:/app/media
      - ./farzone/db.sqlite3:/app/db.sqlite3
    depends_on:
      - farzone
    networks:
      - ttforum-network

networks:
  ttforum-network:
    driver: bridge

volumes:
  staticfiles:
  media:
  db: