version: '3.8'

services:
  farzone:
    build:
      context: .
      dockerfile: Dockerfile.farzone
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - SECRET_KEY=${SECRET_KEY}
      - YANDEX_MAPS_API_KEY=${YANDEX_MAPS_API_KEY}
      - NOTIFIER_URL=http://notifier:8001
      - NOTIFIER_API_KEY=secret-key
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./db:/app/db
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    depends_on:
      - redis
      - notifier
    networks:
      - ttforum-network

  notifier:
    build:
      context: .
      dockerfile: Dockerfile.notifier
    ports:
      - "8001:8001"
    environment:
      - API_KEY=secret-key
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    networks:
      - ttforum-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - ttforum-network

networks:
  ttforum-network:
    driver: bridge

volumes:
  staticfiles:
  media:
  db: