services:
  - type: web
    name: farzone
    env: docker
    dockerfilePath: ./Dockerfile.farzone
    plan: free
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,localhost,127.0.0.1,farzone.onrender.com"
      - key: SECRET_KEY
        sync: false
      - key: YANDEX_MAPS_API_KEY
        sync: false
      - key: NOTIFIER_URL
        value: http://notifier:8001/notifications/
      - key: NOTIFIER_API_KEY
        sync: false
      - key: REDIS_URL
        value: redis://redis:6379/0
    buildCommand: python manage.py collectstatic --noinput && python manage.py migrate

  - type: web
    name: notifier
    env: docker
    dockerfilePath: ./Dockerfile.notifier
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: NOTIFIER_API_KEY
        sync: false

  - type: redis
    name: redis
    ipAllowList: []
    plan: free