services:
  - type: web
    name: farzone
    env: docker
    dockerComposeFile: docker-compose.yml
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1,*.onrender.com
      - key: NOTIFIER_URL
        value: https://notifier.onrender.com
      - key: NOTIFIER_API_KEY
        value: secret-key
      - key: YANDEX_MAPS_API_KEY
        value: 0da8c4de-790a-498b-911e-a8330a5b0a70
      - key: REDIS_URL
        fromService:
        type: redis
        name: farzone_redis
        property: connectionString
    disk:
      - name: sqlite-disk
        mountPath: /app/db/db.sqlite3
        sizeGB: 1
      - name: staticfiles-disk
        mountPath: /app/staticfiles
        sizeGB: 1
      - name: media-disk
        mountPath: /app/media
        sizeGB: 1

  - type: redis
    name: farzone_redis
    plan: free
    maxmemoryPolicy: allkeys-lru

  - type: web
    name: notifier
    env: docker
    dockerComposeFile: docker-compose.yml
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7480135927:AAGwkJlU6iF2aNkAh2gfNtzwLNRwCca5kys
      - key: TELEGRAM_CHAT_ID
        value: 1175923220

