services:
  - type: web
    name: farzone
    env: docker
    dockerComposeFile: docker-compose.yml
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1,*.onrender.com
    disk:
      - name: sqlite-disk
        mountPath: /app/db.sqlite3
        sizeGB: 1
      - name: staticfiles-disk
        mountPath: /app/staticfiles
        sizeGB: 1
      - name: media-disk
        mountPath: /app/media
        sizeGB: 1

  - type: web
    name: notifier
    env: docker
    dockerComposeFile: docker-compose.yml
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7480135927:AAGwkJlU6iF2aNkAh2gfNtzwLNRwCca5kys