databases:
  - name: redis
    databaseName: redis
    plan: free
    region: oregon

services:
  - type: web
    name: farzone
    env: docker
    dockerfilePath: ./Dockerfile.farzone
    plan: free
    region: oregon
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: farzone.onrender.com,*.onrender.com,localhost
      - key: REDIS_URL
        fromDatabase:
          name: redis
          property: connectionString
      - key: YANDEX_MAPS_API_KEY
        sync: false
      - key: NOTIFIER_URL
        value: https://notifier.onrender.com
      - key: NOTIFIER_API_KEY
        value: secret-key

  - type: web
    name: notifier
    env: docker
    dockerfilePath: ./dockerfile.notifier
    plan: free
    region: oregon
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: API_KEY
        value: secret-key