# Generated by Django 5.1.7 on 2025-05-14 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_comment_author_name_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
